[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com;
      script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com;
    """

# This block sets up our scheduled function named "check-finetune-status"
# to run every 15 minutes (*/15 * * * *).
[[functions]]
  name = "check-finetune-status"
  schedule = "*/15 * * * *"

